INFO 2025-05-09 20:40:34,758 autoreload 10168 1840 Watching for file changes with StatReloader
INFO 2025-05-09 20:40:54,285 basehttp 10168 16920 "OPTIONS /api/user/login/ HTTP/1.1" 200 0
ERROR 2025-05-09 20:40:57,670 log 10168 16920 Internal Server Error: /api/user/login/
Traceback (most recent call last):
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: users_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\users\views.py", line 189, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\users\serializers.py", line 384, in validate
    user = authenticate(
        request=self.context.get('request'),
        username=email,  # Using email as username field
        password=password
    )
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\contrib\auth\backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: users_customuser
ERROR 2025-05-09 20:40:58,546 basehttp 10168 16920 "POST /api/user/login/ HTTP/1.1" 500 249434
INFO 2025-05-09 20:47:11,806 autoreload 15620 17588 Watching for file changes with StatReloader
ERROR 2025-05-09 20:47:30,722 log 15620 10476 Internal Server Error: /api/user/login/
Traceback (most recent call last):
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: users_customuser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\users\views.py", line 189, in post
    serializer.is_valid(raise_exception=True)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 225, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\rest_framework\serializers.py", line 447, in run_validation
    value = self.validate(value)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\users\serializers.py", line 384, in validate
    user = authenticate(
        request=self.context.get('request'),
        username=email,  # Using email as username field
        password=password
    )
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\views\decorators\debug.py", line 75, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 114, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\contrib\auth\backends.py", line 65, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\contrib\auth\base_user.py", line 37, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 629, in get
    num = len(clone)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 1935, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1622, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 235, in execute
    return self._record(super().execute, sql, params)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 160, in _record
    return method(sql, params)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Santhanam\OneDrive\Personal\Full stack web development\eduplatform\backend\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: users_customuser
ERROR 2025-05-09 20:47:31,258 basehttp 15620 10476 "POST /api/user/login/ HTTP/1.1" 500 249434
